name: Hyperion
description: Addon plugin for ProjectKorra
author: Moros
version: ${pluginVersion}
main: me.moros.hyperion.Hyperion
depend: [ProjectKorra]
api-version: 1.16
permissions:
  bending.command.hyperion:
    default: true
    description: Shows info about Hyperion.
  bending.command.hyperion.reload:
    default: op
    description: Reload the config of Hyperion.
